FROM gradle:8.0.0-jdk17-alpine AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

ENV DB_HOST=db
ENV DB_USERNAME=admin
ENV DB_PASSWORD=admin
ENV DB_PORT=5432
ENV DB_NAME=development

RUN gradle build --info

FROM eclipse-temurin:17-jre-alpine

EXPOSE 8080

RUN mkdir /app

COPY --from=build /home/gradle/src/build/libs/*.jar /app/creditport-backend.jar
CMD ["java", "-jar", "/app/creditport-backend.jar"]