server:
  servlet:
    context-path: /api/v1
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


management:
  web:
    exposure:
      include: "*"

springdoc:
  api-docs:
    path: "/api-docs"

